### ISSUE TITLE
Can't load or assign any presets from library 

### ISSUE THREAD

**Issue by Barracuda77** [prman-pixar/RenderManForBlender#549]
Can't load into the scene or assign to selected any Material preset in blender 2.79 release
on centos 7 with Renderman 21.5

![screenshot from 2017-09-17 15-26-31](https://user-images.githubusercontent.com/32044472/30525673-c9a83b2c-9bbf-11e7-82d5-b2273d7aa999.png)

**Comment by jzazbert** [comment]
This is caused by the hyphen in the addon filename. I unzipped the addon, renamed the internal folder rendermanforblender_21_5 getting rid of the hyphen, and rezipped it. I made sure the zipfile didnt have a hyphen either for good measure, and then removed and readded the modified addon. It fixed my problem on both windows and linux. I'd recommend removing the hyphen from the release zip files to clear this up.

**Comment by Barracuda77** [comment]
Thank jzazbert, that fixed it for me.

**Comment by Viduttam** [comment]
Yup, this renaming solution works jzazbert! Thanks.

**Comment by SamMcfly** [comment]
I'm having the same issue, and i don't know what is a hyphen...
