### ISSUE TITLE
Overscan Rendering

### ISSUE THREAD

**Issue by earlywill** [prman-pixar/RenderManForBlender#564]
I've done a first pass at implementing overscan rendering, which allows you to add extra pixels to the render outside the display window. For example, a setting of 100x100px adds 50px to each side of the image.

![overscan_options](https://user-images.githubusercontent.com/33976398/35665029-38856f0e-06d9-11e8-8a58-d29575ae307a.jpg)

This is useful if you want a little bit of safety to reframe the image in post, avoid blurring issues near image borders or you need to do some lens distortion.

![overscan](https://user-images.githubusercontent.com/33976398/35664983-1237aa10-06d9-11e8-99a8-0179db55c171.jpg)

Currently it works like this...

1. Set the ScreenWindow and Resolution in the RIB file to the new image area (this doesn't modify the FOV)
2. Runs oiiotool on the renders at the end of the job to set the DisplayWindow back to it's intended format so the view looks correct against your Blender viewport. As a bonus this autocrops the render based on the alpha.

There is one big glaring issue with this that will affect how this is implemented and that's the second point.

I'm currently using oiiotool to set the DisplayWindow as there isn't an existing Renderman tool to do this. Oiiotool is an external tool and would require the user to have it in their PATH. Without this the user would need to reformat the images manually using something like a Reformat node in Nuke - which might not be obvious how to do this. I can add an option "post convert using oiiotool".

Does anyone have any thoughts about this?

**Comment by adminradio** [comment]
I like the idea and see the need for post production, especially for blurring. The option for resetting the display window back should only be available if 'oiiotool' where found. If not, the user should know what somebody had enabled and have to deal with it.

 I'm not fully satisfied with the terms 'width' and 'height' because they have to be recalculated by brain, I would name them something like "Vertical Overscan: 50px" and "Horizontal Overscan: 50px" which describes exactly whats going on: overscanning a single border by 50px. But this is my own point of view and may be biased.

From the fellows of printing post production comes the term **bleed**, which describes the overprinting for cutting the sheet. Typically they are given for any single border (like CSS-Border-Attributes), but mostly used with a single value which is applicable for all four side. I like the wording **bleed** a lot, but didn't know if that would fit here.

**Comment by earlywill** [comment]
Thanks, that's great feedback. It's actually easier to not include the postconvert using oiiotool, currently trying to figure out all the displays that get written out and process isn't obvious. Maybe need to think about oiiotool postconvert as another separate feature (optional add-on 😊), this come from the way I work - with local queue I post convert exr to dpx and then convert those to prores using ffpeg for editing in resolve while comp with the exrs.

Point of overscan width/height is good, more obvious what it's doing. In Katana they offer control over each side, but dealing with lopsided overscan can be tricky which is why I didn't go that option. Bleed could also be used to describe this (especially for print), overscan is a bit more common term in vfx - both katana and nuke use it.

**Comment by adminradio** [comment]
Naming it "overscan" is absolutely fine, even if i came from the printing world I understand immediately what you wanted to do.

I would keep in mind, that the user could have enabled percentage scaling  under **Dimensions** and you have to make clear how do you handle this. Since this is an option for generating final images (in my humble opinion) and percentage scaling is mostly enabled during prerendering, a boolean option for toggle overscanning like the following would do the trick:

`[x] Full size render only`

Should be enabled by default because it impacts render times a lot and  a good description for the property should mention something about "100%", "Dimensions" or so. :-)

You can get the percentage scaling o the current scene with:

`bpy.data.scenes[bpy.context.scene.name].render.resolution_percentage`

**Comment by earlywill** [comment]
I did a lot of my testing at 25%, so I know what you mean (adding 512px to an HD@25% image ends up doubling the intended resolution :) ). I'm thinking the following drop-down.

- Full Size Render Only (default), this only applies overscan when rendering at 100% resolution.
- Relative to Render Percentage, this scales the overscan according to the resolution percentage.
- Absolute Values, renders with the set overscan, ignoring the render percentage.

**Comment by adminradio** [comment]
Even better. Perfect. :)
