### ISSUE TITLE
how to fix cannot find a valid renderman license,Aborting

### ISSUE THREAD

**Issue by luqinchuan** [prman-pixar/RenderManForBlender#611]
can enable the addon,but cant render

**Comment by foreachthing** [comment]
You need to have renderman (from its website https://renderman.pixar.com/store) installed.

**Comment by luqinchuan** [comment]
> You need to have renderman (from its website https://renderman.pixar.com/store) installed.

i have installed it already,twice,still cant render and show the warning

**Comment by prman-pixar** [comment]
This sometimes happens if you tried to install RenderMan in a different hard drive folder. Try looking for pixar.license on your machine and make sure that it is in the directory above RenderMan Pro Server. Normally, if you don't change the install directory, on Windows RenderMan Pro Server goes to:

C:\Program Files\Pixar\RenderManProServer-24.1

and pixar.license is saved in C:\Program Files\Pixar

**Comment by nuzzar** [comment]
I also have this problem. I've managed to install it and run it successfully but after a while it got the license error. I have to renew the license to fix it but after a while the same problem occur again. FYI, the two host id on the licenseapp doesn't match. Is these two host id supposed to match? I've got hyper-v for wsl2 so the first host id might look different depending whether I run wsl2 or not.

**Comment by nuzzar** [comment]
![image](https://user-images.githubusercontent.com/18203407/128515697-78264278-dc5c-4cad-9e19-61ae88853bef.png)

**Comment by nuzzar** [comment]
It turns out in windows 10 there's a feature that's called random address in your wifi settings. This is what caused the problem for me. You need to turn this off otherwise it will change your address and make the license invalid.

**Comment by prman-pixar** [comment]
Glad you figured it out, @nuzzar
