### ISSUE TITLE
lpe light names

### ISSUE THREAD

**Issue by cedricp** [prman-pixar/RenderManForBlender#621]
Hi,
I struggled to make a lpe work. I finally found that the light name in RIB is strangely formatted : 
if I have a light named **lightA** in the scene, I have to write an lpe like this : 
`lpe:C<RS>[<L.'|lightA|lightA-LIGHT'>]`
Is there a way to make it simpler ?

Best regards

**Comment by prman-pixar** [comment]
I think it's easier to use light groups, rather than trying to enter the name of the light directly. With light groups, you can have multiple lights contribute to the same LPE, provided if they are tagged with the same light group name.

1. In the light properties, under Advanced, enter a name for the Light Group.
2. In the RenerMan Displays, under the channel properties, if you look under Advanced, you should see a selection for the light group. 
3. At render time, we will add in the light group after the "L." in the LPE for you.

**Comment by cedricp** [comment]
It makes sense, thank you
