### ISSUE TITLE
Bugs when using render border

### ISSUE THREAD

**Issue by johannes-wilde** [prman-pixar/RenderManForBlender#683]
Final render does not work, when using a render border in the viewport. 
While viewport rendering kind of works with a render border, switching between the render kernels is not possible.

Blender 3.6 on Win11

**Comment by prman-pixar** [comment]
@johannes-wilde  This seems to be working for me. Can you give me a list of steps to follow to reproduce what you're seeing?

**Comment by johannes-wilde** [comment]
Thanks for your reply!

Sure I can wirkte a short guide:

1. Create a Blender scene, it can be empty as well.
2. Create a Camera, go to camera view
3. "ctrl+b" : Drag rendering border over the camera
4. Hit F12 for rendering (does not work for me)

Cheers,

Johannes

**Comment by johannes-wilde** [comment]
Hey,
now it works!
But there is still an issue, when in viewport rendering. If the render border is set to the camera and you move the camera, it gives artefacts and leads sometimes to a crash of Blender.

Here is a screenshot:

![Screenshot 2023-08-07 191304](https://github.com/prman-pixar/RenderManForBlender/assets/71132979/b96a3f68-442c-4e1c-8c89-6c001450c88c)

**Comment by prman-pixar** [comment]
@johannes-wilde thanks for confirming. I'm having a hard time reproducing your new issue. I'll keep digging, but if this is stopping you from using the addon, I would suggest rendering to "it" instead in the meantime.

**Comment by TeaNotes** [comment]
The issue happens for me when rendering region and crop to render is enabled, but only if the render region exceeds the bounds of your viewport. So a simple repro is render with crop to region and zoom in until the crop region boundary goes beyond viewport extents. 

I came here to report this specific issue but didn't want to start a new thread for it. Sorry to revive a thread from a year ago. Any further info you need, let me know.

**Comment by prman-pixar** [comment]
@TeaNotes  do you have a blend file you can share?

**Comment by TeaNotes** [comment]
> @TeaNotes do you have a blend file you can share?

Of course, I've attached a very simple scene, just start viewport render and just zoom in a couple of times, the app crashes when the boundary exceeds the limits of the viewport. I've tried with 4.2 and 3.6, crashes with both. At first I thought it was because of the Omniverse build but it happens with vanilla Blender builds as well.

[crop_region_bug.zip](https://github.com/user-attachments/files/16982363/crop_region_bug.zip)

Anything else you need help with, let me know.

**Comment by prman-pixar** [comment]
Thanks @TeaNotes . I will see if I can take a look at this tomorrow.

**Comment by prman-pixar** [comment]
@TeaNotes  can you see if this patch works for you?
[RenderManForBlender.zip](https://github.com/user-attachments/files/16996105/RenderManForBlender.zip)

**Comment by TeaNotes** [comment]
@prman-pixar it doesn't crash so that's fine, but panning creates this weird artefacting around the render. But it doesn't crash, that's great, I can ignore the weirdness for now.

![image](https://github.com/user-attachments/assets/357ff1d6-6996-45c4-9be2-e2871a97c2de)

Thank you for looking into this so quickly, hopefully the patch will make it's way into the next release. I can keep testing until the artefacts are gone, if that's something you will be addressing.

**Comment by prman-pixar** [comment]
Actually, there's still some issues that I'm running into. Let me address those and I'll provide a new patch for you to test.

**Comment by TeaNotes** [comment]
No problem at all, I'm around for the next 3-4h if there's anything you need tested.

**Comment by TeaNotes** [comment]
So, a bit of a development with this patch. On another scene I have that I can share but not public, with the new patch it just won't render at all, render region remains grey, and trying XPU hard crashes, I will try to see what causes it.

**Comment by prman-pixar** [comment]
@TeaNotes  do you mind trying this patch?

[RenderManForBlender.zip](https://github.com/user-attachments/files/16998638/RenderManForBlender.zip)

**Comment by TeaNotes** [comment]
This patch seems to render the other scenes as well, still artefacts like crazy when moving the view around but it does render my other scene just fine.

**Comment by prman-pixar** [comment]
@TeaNotes  thanks for testing. When you say artefacting, are you talking the region outside the crop border? If so, we don't clear the buffers outside of the border, so could what you're seeing just be remnants of the previous render?

**Comment by TeaNotes** [comment]
My pleasure, thank you for providing a fix so quickly! And yes it's only outside the render region, it is exactly what you've described. I'm maybe used to the behaviour in Maya more :)  But as far as the viewport crashes are concerned, this seems to be fixed as far as my testing so far has gone. 

I'd say this closes the ticket but that's for you to decide.

PS: There is one viewport-related note I wanted to add, it's not a bug report, if anything it is borderline pedantic and mostly irrelevant functionally - if you let the viewport samples play out all the way, the last buffer refresh doesn't happen until you click somewhere, anywhere. It's not something you'd notice without looking at the viewport sampling stats, it's not affecting anything, it doesn't pause the render, just need to click somewhere to get that last refresh.... make of it what you will :))

Thank you again for looking into this, if you need further testing I'd be happy to help.

**Comment by TeaNotes** [comment]
I may have spoken too soon. I have a situation where with border crop enabled, if I tweak a node in the shader tree or disable a modifier, it will crash blender. Will probe this further and come back when I have solid repro steps because at this point I only have this on one file that I can reliably crash. All the above are fine without render region, but with it enabled, it crashes.
